version: '2.2'

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - frontend
      - postgres
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/NS_db
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - backend
    environment:
      REACT_APP_API_URL: "http://localhost:8080"

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgres
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/NS_db
      - --username=admin
      - --password=secret
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: NS_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
