spring:
  application:
    name: NotificationService

  datasource:
    url: jdbc:postgresql://postgres:5432/NS_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ronorothog2003@gmail.com
    password: mjggntyypvhmxrqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3
      delivery-timeout-ms: 120000
    topic:
      email-notifications: email-notifications

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

jwt:
  secret: ${JWT_SECRET:default-secret}
  expiration: 86400000
